CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TEXT);
CREATE TABLE IF NOT EXISTS scans (id INTEGER PRIMARY KEY, source TEXT, domain_name TEXT, started_at TEXT, completed_at TEXT, status TEXT, summary_json TEXT, coverage_json TEXT);
CREATE TABLE IF NOT EXISTS certificate_authorities (id INTEGER PRIMARY KEY, scan_id INTEGER NOT NULL, name TEXT, dns_name TEXT, status TEXT, config_json TEXT);
CREATE TABLE IF NOT EXISTS certificate_templates (id INTEGER PRIMARY KEY, scan_id INTEGER NOT NULL, name TEXT, display_name TEXT, eku TEXT, enrollee_supplies_subject INTEGER, manager_approval INTEGER, authorized_signatures INTEGER, validity_days INTEGER, renewal_days INTEGER, published_to TEXT, raw_json TEXT);
CREATE TABLE IF NOT EXISTS template_permissions (id INTEGER PRIMARY KEY, template_id INTEGER NOT NULL, principal TEXT, can_enroll INTEGER, can_autoenroll INTEGER);
CREATE TABLE IF NOT EXISTS issued_certificates (id INTEGER PRIMARY KEY, scan_id INTEGER NOT NULL, request_id TEXT, requester TEXT, template_name TEXT, subject TEXT, san TEXT, issued_at TEXT, expires_at TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS findings (id INTEGER PRIMARY KEY, scan_id INTEGER NOT NULL, rule_id TEXT, esc_category TEXT, severity TEXT, confidence TEXT, coverage_state TEXT, title TEXT, affected_object TEXT, trigger_conditions TEXT, rationale TEXT, evidence_json TEXT, remediation TEXT, remediation_steps_json TEXT, simulation_summary TEXT, simulation_json TEXT, reference TEXT);
CREATE TABLE IF NOT EXISTS risk_acceptances (id INTEGER PRIMARY KEY, finding_id INTEGER, fingerprint TEXT NOT NULL, object_type TEXT NOT NULL, object_name TEXT NOT NULL, category TEXT NOT NULL, risk_title TEXT NOT NULL, severity TEXT, accepted_by TEXT NOT NULL, accepted_at TEXT, expiry_date TEXT, business_justification TEXT, compensating_control TEXT, status TEXT, scope TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY, actor TEXT, action TEXT, occurred_at TEXT, details_json TEXT);
CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY);
INSERT OR IGNORE INTO schema_migrations(version) VALUES ('001_init');
CREATE TABLE IF NOT EXISTS validation_runs (id INTEGER PRIMARY KEY, finding_id INTEGER NOT NULL, scan_id INTEGER NOT NULL, mode TEXT, recipe_id TEXT, recipe_version TEXT, recipe_hash TEXT, target TEXT, status TEXT, result TEXT, confidence TEXT, summary TEXT, requested_by TEXT, created_at TEXT, started_at TEXT, completed_at TEXT, correlation_id TEXT UNIQUE, safety_json TEXT, evidence_json TEXT);
CREATE TABLE IF NOT EXISTS validation_steps (id INTEGER PRIMARY KEY, validation_run_id INTEGER NOT NULL, sequence INTEGER NOT NULL, step_name TEXT, status TEXT, message TEXT, started_at TEXT, completed_at TEXT, evidence_json TEXT);
CREATE INDEX IF NOT EXISTS ix_validation_runs_finding_id ON validation_runs(finding_id);
CREATE INDEX IF NOT EXISTS ix_validation_runs_scan_id ON validation_runs(scan_id);
CREATE INDEX IF NOT EXISTS ix_validation_runs_created_at ON validation_runs(created_at);
CREATE UNIQUE INDEX IF NOT EXISTS ix_validation_runs_correlation_id ON validation_runs(correlation_id);
CREATE INDEX IF NOT EXISTS ix_validation_steps_validation_run_id ON validation_steps(validation_run_id);
